### PR TITLE
Fix memory leaks and get rid of redundant copies.

### PR DESCRIPTION
**Pull request by kaushiks**
Results in a ~ 50% speedup. Also narrows the gap between libc++'s malloc and jemalloc to ~ 15% that sounds about right to me.

```
tw-mbp-ks:interviewcodecpp kaushik$ CXXFLAGS="-std=c++11 -O2" make main
c++ -std=c++11 -O2    main.cpp   -o main
tw-mbp-ks:interviewcodecpp kaushik$ ./main
Starting
Running benchmark
300 ns/op
295 ns/op
297 ns/op
294 ns/op
296 ns/op
tw-mbp-ks:interviewcodecpp kaushik$ DYLD_INSERT_LIBRARIES=/usr/local/lib/libjemalloc.2.dylib ./main
Starting
Running benchmark
256 ns/op
251 ns/op
249 ns/op
258 ns/op
256 ns/op
tw-mbp-ks:interviewcodecpp kaushik$ valgrind ./main
==43739== Memcheck, a memory error detector
==43739== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==43739== Using Valgrind-3.15.0.GIT and LibVEX; rerun with -h for copyright info
==43739== Command: ./main
==43739== 
--43739-- run: /usr/bin/dsymutil "./main"
warning: no debug symbols in executable (-arch x86_64)
Starting
Running benchmark
7982 ns/op
8006 ns/op
8044 ns/op
7930 ns/op
7947 ns/op
==43739== 
==43739== HEAP SUMMARY:
==43739==     in use at exit: 22,480 bytes in 163 blocks
==43739==   total heap usage: 5,017,519 allocs, 5,017,356 frees, 5,361,546,256 bytes allocated
==43739== 
==43739== LEAK SUMMARY:
==43739==    definitely lost: 0 bytes in 0 blocks
==43739==    indirectly lost: 0 bytes in 0 blocks
==43739==      possibly lost: 72 bytes in 3 blocks
==43739==    still reachable: 4,296 bytes in 7 blocks
==43739==         suppressed: 18,112 bytes in 153 blocks
==43739== Rerun with --leak-check=full to see details of leaked memory
==43739== 
==43739== For lists of detected and suppressed errors, rerun with: -s
==43739== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)
```

### CODE REVIEW

**Comment by sayrer** [comment]
Hmm, does this sort the entities outside the benchmark? I did this in PR https://github.com/spullara/interviewcode/pull/4 but the summary of the repo is "At Twitter I often asked a simple question, render a tweet given the text and an unordered list of its entities"

**Comment by spullara** [comment]
You have to sort the entities per render as they shouldn't come in sorted. This is done to match the way they are in Tweet JSON. Since each type is in its own section they aren't sorted in the JSON and have to be sorted at some point in order for most algorithms to work.

**Comment by spullara** [comment]
It looks like the render() method should take an unordered_set and then the rest of the changes needed follow.

**Comment by kaushiks** [comment]
The benchmark will have to use something other than a set to begin with. Even if I were to create a vector out of the set, and sort it, I'll merely be measuring the time it takes to sort a sorted array - which some sorting algorithms aren't great at.

**Comment by spullara** [comment]
You can just switch to using unordered_set for the data and the API — though I suck at C++ and am having trouble getting the hash function defined for it. Then inside the render method you can make a set from the unordered_set which will sort it.

**Comment by kaushiks** [comment]
in createEntriesList, is the assumption that there could be duplicate entities? Is that why you used a set? (and are now recommending an unordered_set?). If not, theoretically, could it also be a vector<vector<Entity>>?

**Comment by spullara** [comment]
I pushed a possible fix.

**Comment by spullara** [comment]
In a Tweet JSON they come in unsorted so have to be sorted at some point. There will not be overlapping entities by definition. I switched the API and the entry lists to unordered_set (like the Java version). You can see an example here: https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/intro-to-tweet-json

Basically each entity type is its own list so there is no way for them to be sorted by start position as you are reading them from JSON. Part of the original interview exercise was to realize that you need to sort them in order to get to a reasonable algorithm.

**Comment by spullara** [comment]
If it makes more sense for them to be vectors you probably should shuffle the fake generated data after inserting them.

**Comment by kaushiks** [comment]
You want to move them from the unordered_map into the set. Copying will be super expensive.

**Comment by spullara** [comment]
Is there some other way to do it? The Java version copies the references (not the values) into the new ordered list.

**Comment by kaushiks** [comment]
auto entities = set<Entity>(std::make_move_iterator(entitySet.begin()), std::make_move_iterator(entitySet.end()));

**Comment by kaushiks** [comment]
It is still slow (~1500 ns). Will have to take a closer look to see why.

**Comment by kaushiks** [comment]
Ignore my earlier comment. The answer to your question is, yes. To mimic the Java version we'll have to use a ```vector<unordered_set<unique_ptr<Entity>>>``` and then create a temporary ```set<Entry*>``` to consume them in sorted order.

**Comment by spullara** [comment]
If you run it with jemalloc it is pretty fast:

```
macbookpro2016:interviewcodecpp sam$ ./main 
Starting
Running benchmark
1677 ns/op
1617 ns/op
1575 ns/op
1580 ns/op
1602 ns/op
macbookpro2016:interviewcodecpp sam$ DYLD_INSERT_LIBRARIES=/usr/local/lib/libjemalloc.dylib ./main
Starting
Running benchmark
717 ns/op
682 ns/op
682 ns/op
682 ns/op
690 ns/op
```

**Comment by kaushiks** [comment]
Yes, I saw that jemalloc makes it faster, but we should be able to eliminate the copy without destroying the incoming set.

**Pull request merged**
